### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by arojunior** [arojunior/awesome-feed#1]
Create the layout using React

It can help a lot [https://codepen.io/arojunior/pen/ZXJYzM](https://codepen.io/arojunior/pen/ZXJYzM)

This issue should be divided in one issue per component.

- [x] Create Main component #7 
- [x] Create Nav Header component #8 
- [x] Create Profile component #9 
- [x] Create Trending Repositories component #10 
- [x] Create Feed component #11 
- [x] Create Trending Developers component #12

**Comment by Ernoff** [comment]
Just to be clear, you would like someone to help convert the codepen snippet into React components??

**Comment by arojunior** [comment]
First of all, thank you for to be interested. Yes, basically. But that layout is a full copy, need some changes before to don't waste time converting components that we are not going to use.

**Comment by Ernoff** [comment]
Alright that is great!! How do I know the ones you need and the ones you do not want so I could start helping out.

Oh and by the way, thank you for thanking me :)

**Comment by arojunior** [comment]
Nice! I really need help. 

Well, the idea is just use the Twitter layout and populate with Github information, like starred repositories by people you follow, trending repositories and trending developers.
We not going to post anything (not yet, I'm thinking in put an option to replies to make threads in the future), just fetch data from Github API and show. So the "tweet input" is not need, As well the tweet button.

I just made some changes in that Codepen, I think now we can start to work in the React Components.

Feedbacks are welcome.

Thank you so much.

**Comment by Ernoff** [comment]
I sent you a PR... Go through it and let me know what you think
